# Welcome to Jekyll!

# Website settings
title: I can, therefore I am.
description: Abhimanyu's blog,use Jekyll and github pages.
keywords: Abhimanyu,Jalpc,blog,Jekyll,github,gh-pages
baseurl:
url: https://abhimanyu-bitsgoa.github.io/
img_path: /static/assets/img/blog

# author
author:
  name: Abhimanyu
  first_name: Abhimanyu
  last_name: Singh Shekhawat
  cv: https://drive.google.com/file/d/1nVVr6EE1l4x8LJ7grpjaZ3dhR_h8Bk55/view?usp=sharing
  email: abhimanyu.bitsgoa@gmail.com
  facebook_username: aronzx
  github_username: abhimanyu-bitsgoa
  linkedin_id: abhimanyubitsgoa
  avatar: /static/assets/img/landing/Jack.jpeg
  skill_icon1:
    - name: icon-python
    - name: icon-shell
  skill_icon2:
    - name: icon-mongodb
    - name: icon-docker
  desc: I believe in finding smart solutions to complex problems both individual and in teams.Experienced (but not limited to) in OOP, Algorithms, Data Structures and Public Speaking.Not rigid with respect to choice of technology, relatively platform agnostic, and open to adopting the right technology for the task at hand.An Open Source enthusiast and apart from that I enjoy weight training on weekdays and long cycling sessions on weekends.I am always looking for opportunities that can help me hone my skill set so that I can contribute and give back to the society, in a better way.

# comment
disqus:
  name: jalpc

# analytics
## google analytics
ga:
  id: UA-93473370-1

go:
  id: GTM-NHMS8GD

## growingIO
gio:
  # id: a49d4901c7853da9

## donation
donation: on

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
