# Welcome to Jekyll!

# Website settings
title: Abimanyu's Site
description: Jack's blog,use Jekyll and github pages.
keywords: Jack,Jalpc,blog,Jekyll,github,gh-pages
baseurl:
url: https://abhimanyu-bitsgoa.github.io/
img_path: /static/assets/img/blog

# author
author:
  name: Abhimanyu
  first_name: Abhimanyu Singh
  last_name: Shekhawat
  cv: http://cv.jarrekk.com
  email: abhimanyu.bitsgoa@gmail.com
  facebook_username: aronzx
  github_username: abhimanyu-bitsgoa
  linkedin_id: abhimanyubitsgoa
  avatar: /static/assets/img/landing/Jack.jpeg
  skill_icon1:
    - name: icon-python
    - name: icon-shell
  skill_icon2:
    - name: icon-mongodb
    - name: icon-docker
  desc: My info here

# comment
disqus:
  name: jalpc

# analytics
## google analytics
ga:
  id: UA-93473370-1

go:
  id: GTM-NHMS8GD

## growingIO
gio:
  # id: a49d4901c7853da9

## donation
donation: on

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
